---

- hosts: webservers
  user: vagrant
  sudo: True

  vars:
    application: longboxed

  vars_files:
      - vars/initial_provision_vars.yml

  tasks:
    - name: System | Add supervisor group to system
      group: name=supervisor state=present

    - name: System | Add user to supervisor group
      user: name=vagrant group=supervisor

    - name: System | Update repositories (apt-get update)
      apt: update_cache=yes

    - name: Apt | Install initial packages
      action: apt pkg=$item state=installed
      with_items:
        - build-essential
        - python-software-properties

    - name: Apt | Add nginx ppa
      action: apt_repository repo=ppa:nginx/stable state=present

    - name: Apt | Install common packages needed for python application development
      action: apt pkg=$item state=installed
      with_items:
        - libmysqlclient-dev
        - mysql-server
        - mysql-client
        - python-dev
        - python-setuptools
        - python-mysqldb
        - git-core
        - nginx
        - zlib1g-dev
        - redis-server

    - name: pip | Install pip
      action: easy_install name=pip

    - name: pip | Install virtualenv
      action: pip name=$item
      with_items:
        - virtualenv
        - virtualenvwrapper

    - name: System | move bash .profile file into place (for virtualenvwrapper)
      template: src=templates/bash_profile dest=/home/vagrant/.profile

    ##
    # MySQL database setup.
    #
    # 'localhost' needs to be the last item for idempotency, see
    #  http://ansible.cc/docs/modules.html#mysql-user
    - name: MySQL | Update MySQL root password for all root accounts
      mysql_user: name=root host=$item password=$mysql_root_password
      with_items:
        - $ansible_hostname
        - 127.0.0.1
        - ::1
        - localhost

    - name: MySQL | copy .my.cnf file with root password credentials
      template: src=templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

    - name: MySQL | Delete anonymous MySQL server user for $server_hostname
      action: mysql_user user="" host="$server_hostname" state="absent"

    - name: MySQL | Delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"

    - name: MySQL | Remove the MySQL test database
      action: MySQL | mysql_db db=test state=absent

    - name: MySQL | Make sure application database exists in mysql
      mysql_db: name=${application}
                login_host=localhost
                login_user=root
                login_password=${mysql_root_password}
                state=present

    ##
    # Install Supervisor and WSGI
    #
    - name: Supervisor | Install Supervisor with pip
      pip: name=supervisor extra_args=--pre

    - name: uWSGI | Install uWSGI
      pip: name=uwsgi

    ##
    # Nginx setup
    #
    - name: Nginx | Remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: Nginx | Write nginx.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf

    - name: Nginx | Start Nginx at boot
      service: name=nginx state=started enabled=yes

    ##
    # Supervisor setup
    #
    - name: Supervisor | Create supervisord config folder
      action: file dest=/etc/supervisor state=directory owner=root

    - name: Supervisor | Create supervisord config
      action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

    - name: Supervisor | Create supervisord init script
      action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

    - name: Supervisor | Start supervisord service and have it run during system startup
      action: service name=supervisord state=started enabled=yes
