---

- hosts: webservers
  user: longboxed
  sudo: True

  vars:
    app_name: longboxed
    repo_url: https://github.com/timbueno/longboxed.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /srv/webapps
    wsgi_file: wsgi.py
    wsgi_callable: application

  vars_files:
    - vars/external_vars.yml

  tasks:
    - name: Install MySQL
      apt: pkg=$item state=installed
      with_items:
        - mysql-server
        - python-mysqldb