---

- hosts: webservers
  user: vagrant
  sudo: True

  tasks:
    - name: install initial packages
      action: apt pkg=$item state=installed
      with_items:
        - build-essential
        - python-software-properties

    - name: add nginx ppa
      action: apt_repository repo=ppa:nginx/stable state=present

    - name: install common packages needed for python application development
      action: apt pkg=$item state=installed
      with_items:
        - zlib1g-dev
        - mysql-server
        - mysql-client
        - python-dev
        - python-setuptools
        - python-mysqldb
        - git-core
        - nginx
        # - redis-server
        # - libxml2-dev
        # - libfreetype6
        # - libfreetype6-dev
        # - python-psycopg2
        # - python-imaging
        # - libjpeg62
        # - libjpeg62-dev
        # - libpq-dev
        # - libmysqlclient-dev

    - name: install pip
      action: easy_install name=pip

    - name: install virtualenv
      action: pip name=$item
      with_items:
        - virtualenv

    ##
    # MySQL database setup.
    #
    - name: MySQL | Configuration file, my.cnf
      action: template src=templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
      tags: common

    - include: ./common-tasks/mysql-secure.yml
    # - include: ./common-tasks/mysql.yml

    ##
    # Install the rest
    #
    - name: install supervisor with pip
      pip: name=supervisor extra_args=--pre

    - name: install wsgi
      pip: name=uwsgi

    - name: remove default nginx site
      action: file path=/etc/nginx/sites-enabled/default state=absent

    - name: write nginx.conf
      action: template src=templates/nginx.conf dest=/etc/nginx/nginx.conf

    - name: create supervisord config folder
      action: file dest=/etc/supervisor state=directory owner=root

    - name: create supervisord config
      action: template src=templates/supervisord.conf dest=/etc/supervisord.conf

    - name: create supervisord init script
      action: template src=templates/supervisord.sh dest=/etc/init.d/supervisord mode=0755

    - name: start supervisord service and have it run during system startup
      action: service name=supervisord state=started enabled=yes

    - name: create webapps directory
      action: file dest=/srv/webapps state=directory
